"""Generic Player-blog SPA crawler.

Most player newsrooms (ZaloPay, ZaloOA, Shopee seller, TikTok Shop,
Grab Merchant, MoMo, Traveloka) are JS-heavy SPAs that return empty
HTML to httpx. This base class:

  1. Tries httpx first (cheap path, in case static HTML ships)
  2. Falls back to Playwright if HTML looks empty
  3. Extracts links matching a configurable URL pattern
  4. Best-effort article enrichment from the detail page

Each player subclass just configures:
  - LIST_URL(s)
  - URL_PATTERN (regex / startswith) for valid article links
  - LIST_BLOCKLIST (URLs that look like article links but are nav)
"""
from __future__ import annotations

import re
from typing import Optional, Pattern
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode

import httpx
from bs4 import BeautifulSoup
from loguru import logger

from src.config.settings import CRAWL_WINDOW_DAYS
from src.crawlers.base import BaseCrawler
from src.storage.models import (
    ArticleType,
    RawArticle,
    Scope,
    SourceType,
    Status,
)
from src.utils.date_utils import (
    date_from_text,
    extract_published,
    now_utc,
    within_window,
)

# Anchor text fragments that mean "this <a> is a CTA button or nav
# menu entry, not an article". Stripped link text matching one of these
# (case-insensitive, after removing emojis/punctuation) is dropped.
_CTA_TITLE_RE = re.compile(
    r"^("
    r"all|home|community|news|driven by tech|pulse of vietnam|"
    r"thông\s*tin(\s+(chi\s*tiết|mới\s*nhất|từ\s+grab|chương\s*trình))?|"
    r"tạo\s+(chiến\s*dịch|liên\s*kết)\s+ngay|gửi\s+ngay|xem\s+ngay|"
    r"trải\s*nghiệm\s*ngay|đăng\s*ký\s*ngay|nhấn\s*vào\s*đây|"
    r"thông\s*báo|sự\s*kiện|cộng\s*đồng|khuyến\s*mãi|thư\s*viện|"
    r"ưu\s*đãi|driver|merchant|generated by create next app"
    r")\s*$",
    re.IGNORECASE,
)
_PAGINATION_RE = re.compile(r"[?&]page=\d+", re.IGNORECASE)


def _canonical_url(url: str) -> str:
    """Strip tracking query params (ref, utm_*, fbclid) for dedup."""
    parts = urlsplit(url)
    keep = [(k, v) for k, v in parse_qsl(parts.query, keep_blank_values=True)
            if not (k.lower() in {"ref", "fbclid", "gclid"} or k.lower().startswith("utm_"))]
    return urlunsplit((parts.scheme, parts.netloc, parts.path,
                       urlencode(keep), ""))


def _extract_body_text(soup: BeautifulSoup) -> str:
    """Extract main article content from common containers.

    Tries the following in order:
      <article>
      <main>
      <div class*="content"|"article"|"post"|"entry">
      All <p> inside body

    Returns up to 800 chars of joined paragraph text, stripping nav,
    script, style, header, footer, and known noise blocks.
    """
    # Remove noise elements before reading
    for tag in soup.find_all(["script", "style", "nav", "header", "footer",
                              "aside", "form"]):
        tag.decompose()
    # Try semantic containers
    for selector in [
        {"name": "article"},
        {"name": "main"},
        {"name": "div", "class_": re.compile(r"(content|article|post|entry|body)", re.IGNORECASE)},
        {"name": "section", "class_": re.compile(r"(content|article|post)", re.IGNORECASE)},
    ]:
        container = soup.find(**selector)
        if container:
            text = container.get_text(" ", strip=True)
            text = re.sub(r"\s+", " ", text)
            if len(text) >= 80:
                return text[:800]
    # Fallback: join all <p> tags in body
    body = soup.find("body") or soup
    paras = [p.get_text(" ", strip=True) for p in body.find_all("p")]
    paras = [p for p in paras if len(p) > 20]  # drop super-short
    if paras:
        text = " ".join(paras)
        return re.sub(r"\s+", " ", text)[:800]
    return ""


def _looks_like_cta_or_nav(title: str) -> bool:
    if not title:
        return True
    # Strip emojis + symbols, collapse spaces
    cleaned = re.sub(r"[\U0001F300-\U0001FAFF☀-➿]+", "", title).strip(
        " ><«»—–-:|*\t\n")
    cleaned = re.sub(r"\s+", " ", cleaned)
    if len(cleaned) < 5:
        return True
    if _CTA_TITLE_RE.match(cleaned):
        return True
    return False


class PlayerBlogCrawler(BaseCrawler):
    """Subclass + override class attributes."""

    name: str
    base_url: str  # primary list URL
    list_urls: list[str] = []  # additional list pages (optional)
    url_substring: str = "/"  # link must contain this
    article_url_re: Pattern[str] = re.compile(r".*")
    block_paths: set[str] = set()
    domain_prefix: str = ""  # absolute prefix for relative hrefs
    source_type: str = "website"
    type_: str = "players_movement"
    scope: str = "domestic"
    player: str = ""

    def __init__(self, max_items: int = 30, window_days: int = CRAWL_WINDOW_DAYS):
        super().__init__()
        self.max_items = max_items
        self.window_days = window_days
        self._cache: dict[str, dict] = {}

    # ---- URL / link helpers --------------------------------------------

    def _is_article_url(self, href: str) -> bool:
        if not href:
            return False
        if self.url_substring not in href:
            return False
        # Pagination URLs are never articles
        if _PAGINATION_RE.search(href):
            return False
        path = href.split("?")[0].rstrip("/")
        if any(path.endswith(b) for b in self.block_paths):
            return False
        return bool(self.article_url_re.search(path))

    def _absolutise(self, href: str) -> str:
        if href.startswith("http"):
            return href
        if href.startswith("/") and self.domain_prefix:
            return self.domain_prefix + href
        return href

    # ---- Fetch with SPA fallback ---------------------------------------

    async def _fetch_spa(self, client: httpx.AsyncClient, url: str) -> Optional[str]:
        html = await self.fetch(client, url)
        if html and "<a" in html.lower() and len(html) > 5000:
            return html
        from src.utils.playwright_fetch import fetch_html

        logger.info("[{}] SPA empty, trying Playwright for {}", self.name, url)
        return await fetch_html(url)

    # ---- Crawler interface ---------------------------------------------

    async def list_article_urls(self, client: httpx.AsyncClient) -> list[str]:
        all_pages = [self.base_url] + list(self.list_urls)
        urls: list[str] = []
        seen_canonical: set[str] = set()
        for list_url in all_pages:
            html = await self._fetch_spa(client, list_url)
            if not html:
                continue
            soup = BeautifulSoup(html, "html.parser")
            for a in soup.find_all("a", href=True):
                href = self._absolutise(a["href"])
                if not self._is_article_url(href):
                    continue
                title = a.get_text(" ", strip=True)
                # Skip CTA-button anchors and nav-menu links
                if _looks_like_cta_or_nav(title):
                    continue
                # Dedup using URL without ?ref= / ?utm_*
                canonical = _canonical_url(href)
                if canonical in seen_canonical:
                    continue
                seen_canonical.add(canonical)
                # Use canonical URL so /blog/x?ref=A and ...?ref=B collapse.
                if title and canonical not in self._cache:
                    self._cache[canonical] = {"title": title}
                urls.append(canonical)
        return urls[: self.max_items]

    async def parse_article(
        self, client: httpx.AsyncClient, url: str
    ) -> Optional[RawArticle]:
        meta = self._cache.get(url, {})
        title = meta.get("title", "")
        snippet = ""
        published = None

        html = await self.fetch(client, url)
        if html:
            soup = BeautifulSoup(html, "html.parser")
            h1 = soup.find("h1")
            if h1 and h1.get_text(strip=True):
                title = h1.get_text(strip=True)

            # Extract article body — prefer real content over meta description.
            # Voucher / promo pages need detail like "Giảm 30% tối đa 120k đơn
            # từ 500k cho người dùng mới" which lives in the body, not in
            # the (often boilerplate) meta description.
            body = _extract_body_text(soup)
            if body and not _looks_like_cta_or_nav(body[:60]):
                snippet = body[:500]

            # Meta description as fallback when no body content found.
            if not snippet:
                desc = soup.find("meta", attrs={"name": "description"})
                if desc and desc.get("content"):
                    candidate = desc["content"].strip()
                    if candidate and not _looks_like_cta_or_nav(candidate):
                        snippet = candidate

            published = extract_published(soup, url)

        if not title or _looks_like_cta_or_nav(title):
            return None
        if published is None:
            published = date_from_text(f"{title} {snippet}")
        # Priority-0 player blog: keep undated posts (newest-first, capped);
        # drop only when an explicit date is older than the window.
        if published is not None and not within_window(published, self.window_days):
            return None

        return RawArticle(
            id=RawArticle.make_id(url),
            crawled_at=now_utc(),
            source=self.name,
            source_type=SourceType(self.source_type),
            url=url,
            title_original=title,
            content_snippet=snippet,
            published_date=published,
            type=ArticleType(self.type_),
            player=self.player,
            scope=Scope(self.scope),
            status=Status.NEW,
        )
